### ISSUE TITLE
Feature Request: Client-side mode

### ISSUE THREAD

**Issue by Khodyn** [Fuzss/visualworkbench-fabric#1]
When you close a crafting table but leave items in it, it could display the items you had in the slots on the table and when you open the same table again, it automatically moves the items back to their respective slots if you have them.

**Comment by Fuzss** [comment]
Client's can't store such data. Even if I would save the data somewhere locally it would be lost after restarting the client.

**Comment by Khodyn** [comment]
> Client's can't store such data. Even if I would save the data somewhere locally it would be lost after restarting the client.

Okay... and? You don't restart Minecraft often. This isn't a real problem.
